# Generated by Django 4.0.6 on 2022-07-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
