# Generated by Django 4.0.6 on 2022-07-09 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_message_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='description',
            new_name='body',
        ),
    ]
